[package]
name = "ccp_bbr"
version = "0.2.1"
authors = ["Akshay Narayan <akshayn@mit.edu>"]

[dependencies]
clap = "2.29"
portus = "0.6.0"
slog = "2.3"
time = "0.1"

[dependencies.nom]
version = "4"
features = ["verbose-errors"]
